export const FETCH_SAVES = 'FETCH_SAVES';
export const FETCH_SAVES_REJECTED = 'FETCH_SAVES_REJECTED';
export const FETCH_SAVES_FULFILLED = 'FETCH_SAVES_FULFILLED';
export const ADD_SAVE = 'ADD_SAVE';
export const DELETE_SAVE = 'DELETE_SAVE';

export const FETCH_TOPSTORIES = 'FETCH_TOPSTORIES';
export const FETCH_TOPSTORIES_REJECTED = 'FETCH_TOPSTORIES_REJECTED';
export const FETCH_TOPSTORIES_FULFILLED = 'FETCH_TOPSTORIES_FULFILLED';
export const DISMISS_TOPSTORY = 'DISMISS_TOPSTORY';
